- hosts: hdfs_hosts
  become: yes
  roles:
  - role: ssh-hardening
  - role: openstack-hardening
  - { role: os-hardening, os_env_umask: '022' }
  - role: hosts-nodes
  - role: hadoop
  - role: hbase

- hosts: hdfs_journalnodes
  become: yes
  roles:
  - role: hdfs-journalnode

- hosts: zookeepers
  become: yes
  roles:
  - role: zookeeper

- hosts: hdfs_namenodes
  become: yes
  roles:
  - role: hdfs-namenode
  - role: hdfs-zkfc

- hosts: hdfs_datanodes
  become: yes
  roles:
  - role: hdfs-datanode

- hosts: hbase_masters
  become: yes
  roles:
  - role: hbase-master

- hosts: hbase_regionservers
  become: yes
  roles:
  - role: hbase-regionserver
